### ISSUE TITLE
RoleDeniedException not being caught...

### ISSUE THREAD

**Issue by nathangoss** [jeremykenedy/laravel-roles#21]
Thanks Jeremy for this awesome package.

I have followed the steps and verified numerous times, however I am having an issue when logged in as a User with only the User role, and trying to go to: /users

I am expecting the RoleDeniedException to be thrown and handled cleanly, as per the updates suggested to the Handler.php file.

Looking at the logs, I can definitely see that the RoleDeniedException is being thrown:

```
[2018-08-17 08:06:41] local.ERROR: You don't have a required ['admin'] role. {"userId":3,"email":"xxx@xxx.com","exception":"[object] (jeremykenedy\\LaravelRoles\\Exceptions\\RoleDeniedException(code: 0): You don't have a required ['admin'] role. at /Library/WebServer/www/vgsmart/vendor/jeremykenedy/laravel-roles/src/Middleware/VerifyRole.php:42)
[stacktrace]
#0 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): jeremykenedy\\LaravelRoles\\Middleware\\VerifyRole->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'admin')
#1 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#2 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#3 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#4 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#5 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#6 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#7 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#8 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(68): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#25 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#26 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#27 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#28 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#29 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Library/WebServer/www/vgsmart/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#47 /Library/WebServer/www/vgsmart/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#48 /Library/WebServer/www/vgsmart/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#49 {main}
"}
```

<img width="1893" alt="image" src="https://user-images.githubusercontent.com/7982811/44255235-aedf1280-a248-11e8-98a5-37e69d95fa8f.png">

I am using the absolute latest, fresh install of Laravel 5.6.

Any direction would be appreciated.

Thanks mate.

Nathan

**Comment by nathangoss** [comment]
Thanks for explaining how things hang together. That's great.

My issue is that in the Exception Handler (App/Exceptions/Handler.php) the Exception doesn't get recognised as RoleDeniedException.

If I put this as the first line in the render function (in Handler.php):

```
return response()->json(get_class($exception));
```
It returns:
```
"jeremykenedy\\LaravelRoles\\Exceptions\\RoleDeniedException"
```

Yet the call to check if the exception is an instanceof one of your Custom exception classes doesn't pick it up:

```
$userLevelCheck = $exception instanceof \jeremykenedy\LaravelRoles\Exceptions\RoleDeniedException ||
        $exception instanceof \jeremykenedy\LaravelRoles\Exceptions\RoleDeniedException ||
        $exception instanceof \jeremykenedy\LaravelRoles\Exceptions\PermissionDeniedException ||
        $exception instanceof \jeremykenedy\LaravelRoles\Exceptions\LevelDeniedException;

        if ($userLevelCheck) {

            if ($request->expectsJson()) {
                return Response::json(array(
                    'error'    =>  403,
                    'message'   =>  'Unauthorized.'
                ), 403);
            }

            abort(403);
        }
```

**Comment by jeremykenedy** [comment]
Hi Nathan,

I have tried to duplicate the issue on a fresh instance of laravel and am unable to replicate the error at this time.  Are you still having this issue?

For reference,

Here is my update method in `\App\Exceptions\Handler.php`

```
    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $exception
     * @return \Illuminate\Http\Response
     */
    public function render($request, Exception $exception)
    {

        $userLevelCheck = $exception instanceof \jeremykenedy\LaravelRoles\Exceptions\RoleDeniedException ||
            $exception instanceof \jeremykenedy\LaravelRoles\Exceptions\RoleDeniedException ||
            $exception instanceof \jeremykenedy\LaravelRoles\Exceptions\PermissionDeniedException ||
            $exception instanceof \jeremykenedy\LaravelRoles\Exceptions\LevelDeniedException;

        if ($userLevelCheck) {
            if ($request->expectsJson()) {
                return Response::json([
                    'error'   => 403,
                    'message' => 'Unauthorized.',
                ], 403);
            }

            abort(403);
        }

        return parent::render($request, $exception);
    }
```

Did you happen to add the `role` to `protected $routeMiddleware` in `\App\Http\Kernel.php`?

That would look something like:
```
    protected $routeMiddleware = [
        ...
        'role' => \jeremykenedy\LaravelRoles\Middleware\VerifyRole::class,
    ];
```

**Comment by jeremykenedy** [comment]
Is this still an issue?

**Comment by jeremykenedy** [comment]
Closing the issue for now. let me know if it persists and please provide duplication steps.

**Comment by syedhassan25** [comment]
hi Jeremy your role package owsum but i have an issue for using this package because i assign  to role user but and assign permission to role but some time permision work  sometime s not wahat is the best way to create role with permission itry something like this to create role and permission  create and update


 public function update_role(Request $request)
    {
        $id = $request->id;

        if($id > 0)
        {
            $row = DB::table('roles')->orderBy('id', 'desc')->first();
            DB::table('roles')->where('id',$id)->update([

                'name'=>$request->input('title'),
                'slug'=>strtolower(str_replace(' ', '', $request->input('title'))),
                'description'=>$request->input('notice'),
                'updated_at'=>date('Y-m-d H:i:s')


            ]);
            
             $role = config('roles.models.role')::find($id);
             $role->detachAllPermissions();
             $permissions =  $request->input('permissions');
             if(isset($permissions)){
              
                 if(count($permissions) > 0){
                     foreach($permissions as $row){
                    
                     $role->attachPermission($row); // permission attached to a role
                 }
                 }
             }


            return response()->json(['code'=>'2']);

        }else{

            $row = DB::table('roles')->orderBy('id', 'desc')->first();
            config('roles.models.role')::create([
                'name'=>$request->input('title'),
                'slug'=>strtolower(str_replace(' ', '', $request->input('title'))),
                'description'=>$request->input('notice'),
                'level'=>$row->level + 1,
                'created_at'=>date('Y-m-d H:i:s')
            ]);
            
             $id =  DB::getPdo()->lastInsertId();
            
                $role = config('roles.models.role')::find($id);
             $role->detachAllPermissions();
             $permissions =  $request->input('permissions');
             if(isset($permissions)){
              
                 if(count($permissions) > 0){
                     foreach($permissions as $row){
                    
                     $role->attachPermission($row); // permission attached to a role
                 }
                 }
             }


            return response()->json(['code'=>'1']);

        }
    }

**Comment by syedhassan25** [comment]
![image](https://user-images.githubusercontent.com/23033000/69360016-96f80900-0cab-11ea-91ae-5a61bc9c4045.png)

**Comment by jeremykenedy** [comment]
Check out the methods in these traits:
https://github.com/jeremykenedy/laravel-roles/blob/master/src/Traits/HasRoleAndPermission.php

It may have some solutions you are looking for attaching and detaching persmissions and roles to a user.

For seeing how the permissions get attached to a role I would checkout this trait:
https://github.com/jeremykenedy/laravel-roles/blob/master/src/Traits/RolesAndPermissionsHelpersTrait.php

For checking on permission for various requests I would recommend using a Request Class like this:
https://github.com/jeremykenedy/jeremykenedy.com/blob/master/app/Http/Requests/StorePostRequest.php

And you can call that like this in your controller:
https://github.com/jeremykenedy/jeremykenedy.com/blob/master/app/Http/Controllers/Admin/PostController.php#L63

I hope that helps.

**Comment by syedhassan25** [comment]
Hi jeremy not working these links  beacuse i am using laravel 5.7  please help beacuse i am stuck...  please provide me some example of code  create user with attached  role  and attached  multiple permission to attached role...

**Comment by jeremykenedy** [comment]
It’s in the readme.
